version: '3'
services:
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - name=value
    volumes:
      - .:/coding
    command: >
      sh -c "
        python --version && 
        pytest --version &&
        sleep infinity" 